void imprimeArray(ArrayProgramas*);
void atualizaVariavel(ProcessManager**, int, int);
void somaVariavel(ProcessManager**, int, int);
void subtraiVariavel(ProcessManager**, int, int);
void bloqueiaProcessoSimulado();
void terminaProcessoSimulado();
void criaNovoProcessoSimulado(int);
void armazenarPrograma(ArrayProgramas**, char*);
void substituiPrograma(ArrayProgramas**, ProcessManager**, char*, int);
void verificarInstrucao(char, ProcessManager**, int, ArrayProgramas**, int, int);