void imprimeArray(ArrayProgramas **arr, int);
void atualizaVariavel(ProcessManager**, int, int);
void somaVariavel(ProcessManager**, int, int);
void subtraiVariavel(ProcessManager**, int, int);
void bloqueiaProcessoSimulado();
void terminaProcessoSimulado();
void criaNovoProcessoSimulado(int);
void substituiPrograma();
void armazenarPrograma(ArrayProgramas***, int);
void verificarInstrucao(char, ProcessManager**, int, int);