void imprimeArray(ArrayProgramas***, int, int);
void atualizaVariavel(ProcessManager**, int);
void somaVariavel(ProcessManager**, int);
void subtraiVariavel(ProcessManager**, int);
void bloqueiaProcessoSimulado();
void terminaProcessoSimulado();
void criaNovoProcessoSimulado(int);
void substituiPrograma();
void armazenarPrograma(ArrayProgramas***, int, int*);
void verificarInstrucao(char, ProcessManager**, int, ArrayProgramas***, int);